export interface Tour {
  id: string;
  slug: string;
  name: string;
  city: 'Prague' | 'Budapest' | 'Vienna' | 'Krakow';
  language: 'en' | 'es' | 'it';
  duration: string;
  basePrice: number;
  images: string[];
  description: string;
  itinerary: { stop: string; description: string; durationMin: number }[];
  capacity: number;
  rating: number;
  reviewCount: number;
  status: 'Active' | 'Draft' | 'Paused';
  bookingsThisMonth: number;
  revenueThisMonth: number;
  type?: 'Walking' | 'Food' | 'Day Trip' | 'Bike' | 'Boat';
}

import { sceneImage } from '@/lib/scene-image';

// Kept as a no-op placeholder so the rest of the file doesn't churn —
// every tour's images are overridden after the array below.
const pragueImg = (_id: string) => '';

export const tours: Tour[] = [
  {
    id: 't1',
    slug: 'old-town-astronomical-clock',
    name: 'Old Town & Astronomical Clock Walking Tour',
    city: 'Prague',
    language: 'en',
    duration: '3 hours',
    basePrice: 25,
    images: [
      pragueImg('photo-1541849548-206242a477bf'),
      pragueImg('photo-1513807016779-d51c0c026263'),
      pragueImg('photo-1519677100203-a0e668c92439'),
    ],
    description:
      'Explore the heart of Prague, the Old Town Square, and witness the magic of the 600-year-old Astronomical Clock with a local historian.',
    itinerary: [
      { stop: 'Old Town Square', description: 'Meeting point at the Jan Hus Memorial.', durationMin: 15 },
      { stop: 'Astronomical Clock', description: 'Watch the hourly Apostles parade.', durationMin: 20 },
      { stop: 'Tyn Church', description: 'Admire the Gothic architecture.', durationMin: 30 },
      { stop: 'Jewish Quarter', description: 'Walk through the historic Josefov district.', durationMin: 45 },
      { stop: 'Powder Tower', description: 'Climb the gothic gate for panoramic views.', durationMin: 30 },
    ],
    capacity: 20,
    rating: 4.9,
    reviewCount: 1250,
    status: 'Active',
    bookingsThisMonth: 145,
    revenueThisMonth: 3625,
    type: 'Walking',
  },
  {
    id: 't2',
    slug: 'prague-castle-lesser-town',
    name: 'Prague Castle & Lesser Town',
    city: 'Prague',
    language: 'es',
    duration: '4 hours',
    basePrice: 35,
    images: [
      pragueImg('photo-1527613426441-4da17471b66d'),
      pragueImg('photo-1592906209472-a36b1f3782ef'),
    ],
    description:
      "A deep dive into the world's largest ancient castle complex and the charming Lesser Town (Mala Strana).",
    itinerary: [
      { stop: 'St. Vitus Cathedral', description: 'The spiritual symbol of the Czech state.', durationMin: 45 },
      { stop: 'Old Royal Palace', description: 'The original residence of Bohemian princes.', durationMin: 30 },
      { stop: 'Golden Lane', description: 'Tiny colorful houses where Franz Kafka lived.', durationMin: 30 },
      { stop: 'Charles Bridge', description: 'Walk across the iconic 14th-century bridge.', durationMin: 30 },
    ],
    capacity: 15,
    rating: 4.8,
    reviewCount: 890,
    status: 'Active',
    bookingsThisMonth: 92,
    revenueThisMonth: 3220,
    type: 'Walking',
  },
  {
    id: 't3',
    slug: 'beer-bohemia-local-pub-tour',
    name: 'Beer & Bohemia: Local Pub Tour',
    city: 'Prague',
    language: 'en',
    duration: '3.5 hours',
    basePrice: 45,
    images: [
      pragueImg('photo-1535958636474-b021ee887b13'),
      pragueImg('photo-1568644396922-5c3bfae12521'),
    ],
    description:
      'Taste the best of Czech beer culture in authentic local pubs away from the tourist traps. Tastings included.',
    itinerary: [
      { stop: 'Local Microbrewery', description: 'Tasting of seasonal craft beers.', durationMin: 60 },
      { stop: 'Traditional Pub', description: 'Learn about the history of Pilsner Urquell.', durationMin: 60 },
      { stop: 'Gourmet Pub', description: 'Beer pairings with traditional Czech snacks.', durationMin: 60 },
    ],
    capacity: 12,
    rating: 5.0,
    reviewCount: 420,
    status: 'Active',
    bookingsThisMonth: 58,
    revenueThisMonth: 2610,
    type: 'Food',
  },
  {
    id: 't4',
    slug: 'communist-prague-cold-war',
    name: 'Communist Prague: A Cold War Story',
    city: 'Prague',
    language: 'en',
    duration: '2.5 hours',
    basePrice: 22,
    images: [pragueImg('photo-1525857597365-5f6dbff2e36e')],
    description:
      'Walk through the streets that shaped the Velvet Revolution and hear stories from those who lived behind the Iron Curtain.',
    itinerary: [
      { stop: 'Wenceslas Square', description: '1968 invasion site briefing.', durationMin: 30 },
      { stop: 'Communism Museum', description: 'Curated exhibition walk-through.', durationMin: 60 },
      { stop: 'National Memorial', description: 'Site of self-immolation by Jan Palach.', durationMin: 30 },
    ],
    capacity: 18,
    rating: 4.8,
    reviewCount: 612,
    status: 'Active',
    bookingsThisMonth: 73,
    revenueThisMonth: 1606,
    type: 'Walking',
  },
  {
    id: 't5',
    slug: 'jewish-quarter-walking-tour',
    name: 'Jewish Quarter Walking Tour',
    city: 'Prague',
    language: 'en',
    duration: '2 hours',
    basePrice: 28,
    images: [pragueImg('photo-1571115764595-644a1f56a55c')],
    description:
      'Discover Josefov, one of the most preserved Jewish quarters in Europe, with stops at six historic synagogues.',
    itinerary: [
      { stop: 'Old-New Synagogue', description: "Europe's oldest active synagogue.", durationMin: 30 },
      { stop: 'Old Jewish Cemetery', description: '12,000 layered graves dating to 1439.', durationMin: 40 },
      { stop: 'Spanish Synagogue', description: 'Moorish revival masterpiece.', durationMin: 30 },
    ],
    capacity: 16,
    rating: 4.9,
    reviewCount: 478,
    status: 'Active',
    bookingsThisMonth: 64,
    revenueThisMonth: 1792,
    type: 'Walking',
  },
  {
    id: 't6',
    slug: 'vltava-river-cruise',
    name: 'Vltava River Cruise',
    city: 'Prague',
    language: 'en',
    duration: '1.5 hours',
    basePrice: 18,
    images: [pragueImg('photo-1564507592333-c60657eea523')],
    description:
      'See Prague from the water with a glass of Bohemian wine, sailing past Charles Bridge and the National Theatre.',
    itinerary: [
      { stop: 'Cechuv Bridge Dock', description: 'Boarding and welcome drink.', durationMin: 15 },
      { stop: 'Charles Bridge Pass', description: 'Best photo angle in the city.', durationMin: 30 },
      { stop: 'National Theatre View', description: 'Sunset return loop.', durationMin: 45 },
    ],
    capacity: 60,
    rating: 4.6,
    reviewCount: 980,
    status: 'Active',
    bookingsThisMonth: 210,
    revenueThisMonth: 3780,
    type: 'Boat',
  },
  {
    id: 't7',
    slug: 'charles-bridge-by-night',
    name: 'Charles Bridge by Night',
    city: 'Prague',
    language: 'en',
    duration: '1.5 hours',
    basePrice: 15,
    images: [pragueImg('photo-1519677100203-a0e668c92439')],
    description:
      'A photographic and ghost-story walk across the 14th-century bridge after the crowds have gone home.',
    itinerary: [
      { stop: 'Old Town Bridge Tower', description: 'Gothic gateway introduction.', durationMin: 20 },
      { stop: 'St. John of Nepomuk', description: 'Touch the statue for good luck.', durationMin: 30 },
      { stop: 'Kampa Island', description: 'Sunset photos over the Vltava.', durationMin: 40 },
    ],
    capacity: 14,
    rating: 4.9,
    reviewCount: 320,
    status: 'Active',
    bookingsThisMonth: 96,
    revenueThisMonth: 1440,
    type: 'Walking',
  },
  {
    id: 't8',
    slug: 'czech-food-drink-tasting',
    name: 'Czech Food & Drink Tasting',
    city: 'Prague',
    language: 'en',
    duration: '3 hours',
    basePrice: 55,
    images: [pragueImg('photo-1559762717-99c81ac85459')],
    description:
      'Six tastings across the Old Town: trdelnik, svickova, becherovka, kolache, and more — with a local chef host.',
    itinerary: [
      { stop: 'Havelska Market', description: 'Czech cheese and pickles tasting.', durationMin: 30 },
      { stop: 'Lokal U Bile Kuzelky', description: 'Svickova and Pilsner pairing.', durationMin: 60 },
      { stop: 'Cafe Louvre', description: 'Kolache and coffee finale.', durationMin: 45 },
    ],
    capacity: 10,
    rating: 4.9,
    reviewCount: 280,
    status: 'Active',
    bookingsThisMonth: 44,
    revenueThisMonth: 2420,
    type: 'Food',
  },
  {
    id: 't9',
    slug: 'prague-zoo-family-day',
    name: 'Prague Zoo Family Day',
    city: 'Prague',
    language: 'en',
    duration: '5 hours',
    basePrice: 32,
    images: [pragueImg('photo-1547721064-da6cfb341d50')],
    description:
      'A guided family experience at one of the top-rated zoos in the world, with priority entry and a kids activity pack.',
    itinerary: [
      { stop: 'Main Entrance', description: 'Priority entry and welcome pack.', durationMin: 15 },
      { stop: 'African Pavilion', description: 'Feeding time with the gorillas.', durationMin: 90 },
      { stop: 'Indonesian Jungle', description: 'Tropical hall walkthrough.', durationMin: 90 },
    ],
    capacity: 20,
    rating: 4.7,
    reviewCount: 415,
    status: 'Active',
    bookingsThisMonth: 38,
    revenueThisMonth: 1216,
    type: 'Day Trip',
  },
  {
    id: 't10',
    slug: 'karlstejn-castle-day-trip',
    name: 'Karlstejn Castle Day Trip',
    city: 'Prague',
    language: 'en',
    duration: '7 hours',
    basePrice: 65,
    images: [pragueImg('photo-1605362404107-5cee0e7afe61')],
    description:
      'Day trip to the gothic castle commissioned by Emperor Charles IV. Round-trip transport from central Prague.',
    itinerary: [
      { stop: 'Pickup Wenceslas Square', description: 'Coach departs at 09:00 sharp.', durationMin: 60 },
      { stop: 'Karlstejn Village', description: 'Lunch break and gear up for the climb.', durationMin: 60 },
      { stop: 'Castle Interiors Tour', description: 'Chapel of the Holy Cross.', durationMin: 120 },
    ],
    capacity: 30,
    rating: 4.8,
    reviewCount: 540,
    status: 'Active',
    bookingsThisMonth: 26,
    revenueThisMonth: 1690,
    type: 'Day Trip',
  },
  {
    id: 't11',
    slug: 'bohemian-switzerland-hike',
    name: 'Bohemian Switzerland Hike',
    city: 'Prague',
    language: 'en',
    duration: '10 hours',
    basePrice: 85,
    images: [pragueImg('photo-1500382017468-9049fed747ef')],
    description:
      'Sandstone gorges, the Pravcicka Brana arch, and a quiet boat ride through the Edmund Gorge.',
    itinerary: [
      { stop: 'Pickup at hotel', description: 'Group transfer in modern van.', durationMin: 120 },
      { stop: 'Pravcicka Brana arch', description: 'Largest natural arch in Europe.', durationMin: 90 },
      { stop: 'Kamenice Gorge boat', description: 'Quiet poled boats through canyon.', durationMin: 90 },
    ],
    capacity: 16,
    rating: 5.0,
    reviewCount: 195,
    status: 'Active',
    bookingsThisMonth: 14,
    revenueThisMonth: 1190,
    type: 'Day Trip',
  },
  {
    id: 't12',
    slug: 'photographers-prague',
    name: "Photographer's Prague",
    city: 'Prague',
    language: 'en',
    duration: '3 hours',
    basePrice: 38,
    images: [pragueImg('photo-1546412414-e1885259563a')],
    description:
      'Sunrise photo walk with a Prague-based photographer, hitting six iconic vantage points with personal coaching.',
    itinerary: [
      { stop: 'Letna Park', description: 'Sunrise over the Vltava bridges.', durationMin: 60 },
      { stop: 'Old Town Bridge Tower', description: 'Wide-angle technique workshop.', durationMin: 60 },
      { stop: 'Vysehrad', description: 'Compose with leading lines.', durationMin: 60 },
    ],
    capacity: 8,
    rating: 5.0,
    reviewCount: 96,
    status: 'Draft',
    bookingsThisMonth: 0,
    revenueThisMonth: 0,
    type: 'Walking',
  },

  {
    id: 't13',
    slug: 'buda-castle-fishermans-bastion',
    name: "Buda Castle & Fisherman's Bastion",
    city: 'Budapest',
    language: 'en',
    duration: '3 hours',
    basePrice: 28,
    images: [pragueImg('photo-1551882547-ff43c63cd53e')],
    description:
      'Discover the historic Castle District of Budapest with panoramic views over the Danube.',
    itinerary: [
      { stop: 'Matthias Church', description: 'Stunning 13th-century church.', durationMin: 40 },
      { stop: "Fisherman's Bastion", description: 'Neo-Romanesque terrace with the best views.', durationMin: 30 },
      { stop: 'Buda Castle', description: 'Explore the royal palace grounds.', durationMin: 60 },
    ],
    capacity: 25,
    rating: 4.9,
    reviewCount: 750,
    status: 'Active',
    bookingsThisMonth: 110,
    revenueThisMonth: 3080,
    type: 'Walking',
  },
  {
    id: 't14',
    slug: 'parliament-heroes-square',
    name: "Hungarian Parliament & Heroes' Square",
    city: 'Budapest',
    language: 'en',
    duration: '3.5 hours',
    basePrice: 32,
    images: [pragueImg('photo-1565294948523-37077c12d20c')],
    description: 'The grand boulevards of Pest, from the neo-Gothic parliament to the Millennium Monument.',
    itinerary: [
      { stop: 'Parliament Square', description: 'Exterior tour, changing of the guard.', durationMin: 45 },
      { stop: "St. Stephen's Basilica", description: 'Climb the dome for city views.', durationMin: 45 },
      { stop: "Heroes' Square", description: 'Millennium Monument and the seven chieftains.', durationMin: 60 },
    ],
    capacity: 22,
    rating: 4.7,
    reviewCount: 530,
    status: 'Active',
    bookingsThisMonth: 78,
    revenueThisMonth: 2496,
    type: 'Walking',
  },
  {
    id: 't15',
    slug: 'thermal-baths-experience',
    name: 'Thermal Baths Experience',
    city: 'Budapest',
    language: 'en',
    duration: '4 hours',
    basePrice: 48,
    images: [pragueImg('photo-1572177812156-58036aae439c')],
    description: 'Skip-the-line entry to Szechenyi Baths plus a private cabin and a Hungarian wine snack.',
    itinerary: [
      { stop: 'Szechenyi Entry', description: 'Locker, towel, robe included.', durationMin: 30 },
      { stop: 'Outdoor pools', description: 'The famous chess players pool.', durationMin: 120 },
      { stop: 'Snack lounge', description: 'Tokaj wine and langos.', durationMin: 30 },
    ],
    capacity: 12,
    rating: 4.8,
    reviewCount: 612,
    status: 'Active',
    bookingsThisMonth: 92,
    revenueThisMonth: 4416,
    type: 'Day Trip',
  },
  {
    id: 't16',
    slug: 'budapest-ruin-bar-crawl',
    name: 'Budapest Ruin Bar Crawl',
    city: 'Budapest',
    language: 'en',
    duration: '4 hours',
    basePrice: 35,
    images: [pragueImg('photo-1530103862676-de8c9debad1d')],
    description:
      "Visit four iconic ruin bars in District VII, with two welcome shots and a young local host's playlist.",
    itinerary: [
      { stop: 'Szimpla Kert', description: 'The original ruin bar.', durationMin: 60 },
      { stop: 'Instant', description: 'Multi-room party labyrinth.', durationMin: 60 },
      { stop: 'Anker Klub', description: 'Live DJ rooftop.', durationMin: 60 },
    ],
    capacity: 15,
    rating: 4.9,
    reviewCount: 405,
    status: 'Active',
    bookingsThisMonth: 66,
    revenueThisMonth: 2310,
    type: 'Food',
  },
  {
    id: 't17',
    slug: 'danube-sunset-cruise',
    name: 'Danube Sunset Cruise',
    city: 'Budapest',
    language: 'en',
    duration: '2 hours',
    basePrice: 30,
    images: [pragueImg('photo-1583500178690-f7fd39c8a3d8')],
    description: 'The most photogenic hour in Budapest, with a glass of Tokaji and live audio commentary in 8 languages.',
    itinerary: [
      { stop: 'Vigado Dock', description: 'Boarding and welcome drink.', durationMin: 20 },
      { stop: 'Parliament pass', description: 'Best photo angle.', durationMin: 40 },
      { stop: 'Chain Bridge return', description: 'Sunset finale.', durationMin: 60 },
    ],
    capacity: 80,
    rating: 4.6,
    reviewCount: 1120,
    status: 'Active',
    bookingsThisMonth: 188,
    revenueThisMonth: 5640,
    type: 'Boat',
  },
  {
    id: 't18',
    slug: 'jewish-quarter-holocaust-history',
    name: 'Jewish Quarter & Holocaust History',
    city: 'Budapest',
    language: 'en',
    duration: '3 hours',
    basePrice: 30,
    images: [pragueImg('photo-1581922814484-0b48460b7010')],
    description: 'The Dohany Street Synagogue, the Shoes on the Danube memorial, and the ghetto walls of District VII.',
    itinerary: [
      { stop: 'Dohany Synagogue', description: 'Largest synagogue in Europe.', durationMin: 45 },
      { stop: 'Tree of Life Memorial', description: 'Names of 600,000 Hungarian victims.', durationMin: 30 },
      { stop: 'Shoes on the Danube', description: 'Lighting a candle of remembrance.', durationMin: 30 },
    ],
    capacity: 18,
    rating: 4.9,
    reviewCount: 380,
    status: 'Active',
    bookingsThisMonth: 52,
    revenueThisMonth: 1560,
    type: 'Walking',
  },

  {
    id: 't19',
    slug: 'imperial-vienna-walking-tour',
    name: 'Imperial Vienna Walking Tour',
    city: 'Vienna',
    language: 'en',
    duration: '2.5 hours',
    basePrice: 22,
    images: [pragueImg('photo-1516550893923-42d28e5677af')],
    description: 'Walk through the footsteps of the Habsburgs and explore the grandeur of the Austrian capital.',
    itinerary: [
      { stop: 'Hofburg Palace', description: 'Former winter residence of the imperial family.', durationMin: 60 },
      { stop: "St. Stephen's Cathedral", description: 'The Gothic symbol of Vienna.', durationMin: 30 },
      { stop: 'Ringstrasse', description: 'See the State Opera and Parliament.', durationMin: 30 },
    ],
    capacity: 30,
    rating: 4.7,
    reviewCount: 560,
    status: 'Active',
    bookingsThisMonth: 85,
    revenueThisMonth: 1870,
    type: 'Walking',
  },
  {
    id: 't20',
    slug: 'schonbrunn-palace-half-day',
    name: 'Schonbrunn Palace Half-Day',
    city: 'Vienna',
    language: 'en',
    duration: '4 hours',
    basePrice: 42,
    images: [pragueImg('photo-1573547429747-72e85af8a4e2')],
    description: "Skip-the-line entry to the imperial summer residence and a guided walk through Sisi's apartments.",
    itinerary: [
      { stop: 'Schonbrunn Entrance', description: 'Audio guide pickup.', durationMin: 15 },
      { stop: 'State Apartments', description: '40 rooms of the imperial family.', durationMin: 90 },
      { stop: 'Gloriette', description: 'Climb for the city skyline view.', durationMin: 60 },
    ],
    capacity: 20,
    rating: 4.8,
    reviewCount: 410,
    status: 'Active',
    bookingsThisMonth: 64,
    revenueThisMonth: 2688,
    type: 'Day Trip',
  },
  {
    id: 't21',
    slug: 'mozart-music-trail',
    name: 'Mozart & Music Trail',
    city: 'Vienna',
    language: 'en',
    duration: '2 hours',
    basePrice: 26,
    images: [pragueImg('photo-1467810563316-b5476525c0f9')],
    description: "Trace Mozart's footsteps from the Mozarthaus to the Vienna State Opera with a classical musician guide.",
    itinerary: [
      { stop: 'Mozarthaus Vienna', description: 'His only surviving Viennese residence.', durationMin: 60 },
      { stop: 'Vienna State Opera', description: 'Exterior tour and ticket tips.', durationMin: 40 },
      { stop: 'Cafe Sacher', description: 'Optional sachertorte stop.', durationMin: 20 },
    ],
    capacity: 12,
    rating: 4.9,
    reviewCount: 240,
    status: 'Active',
    bookingsThisMonth: 36,
    revenueThisMonth: 936,
    type: 'Walking',
  },
  {
    id: 't22',
    slug: 'vienna-coffee-house-culture',
    name: 'Vienna Coffee House Culture',
    city: 'Vienna',
    language: 'en',
    duration: '2.5 hours',
    basePrice: 34,
    images: [pragueImg('photo-1495474472287-4d71bcdd2085')],
    description: 'Three legendary coffee houses, three Viennese pastries, and a deep dive into UNESCO-listed coffee culture.',
    itinerary: [
      { stop: 'Cafe Central', description: 'Apfelstrudel tasting.', durationMin: 45 },
      { stop: 'Cafe Hawelka', description: 'Family-owned since 1939.', durationMin: 45 },
      { stop: 'Cafe Demel', description: 'Imperial confectioner finale.', durationMin: 45 },
    ],
    capacity: 10,
    rating: 4.9,
    reviewCount: 175,
    status: 'Paused',
    bookingsThisMonth: 0,
    revenueThisMonth: 0,
    type: 'Food',
  },
];

const cityImages: Record<string, string[]> = {
  'Prague': [
    'photo-1541849548-206242a477bf',
    'photo-1527613426441-4da17471b66d',
    'photo-1519677100203-a0e668c92439',
    'photo-1564507592333-c60657eea523',
    'photo-1535958636474-b021ee887b13',
    'photo-1525857597365-5f6dbff2e36e',
    'photo-1571115764595-644a1f56a55c',
    'photo-1559762717-99c81ac85459'
  ],
  'Budapest': [
    'photo-1551882547-ff43c63cd53e',
    'photo-1565294948523-37077c12d20c',
    'photo-1572177812156-58036aae439c',
    'photo-1530103862676-de8c9debad1d',
    'photo-1583500178690-f7fd39c8a3d8',
    'photo-1581922814484-0b48460b7010'
  ],
  'Vienna': [
    'photo-1516550893923-42d28e5677af',
    'photo-1573547429747-72e85af8a4e2',
    'photo-1467810563316-b5476525c0f9',
    'photo-1495474472287-4d71bcdd2085',
    'photo-1527613426441-4da17471b66d'
  ],
  'Krakow': [
    'photo-1516147539103-45ab603c626c',
    'photo-1515162305285-0293e4767cc2',
    'photo-1541849548-206242a477bf'
  ]
};

tours.forEach((t, i) => {
  const ids = cityImages[t.city] || cityImages['Prague'];
  t.images = [
    `https://images.unsplash.com/${ids[i % ids.length]}?auto=format&fit=crop&w=1200&q=80`,
    `https://images.unsplash.com/${ids[(i + 1) % ids.length]}?auto=format&fit=crop&w=1200&q=80`,
    `https://images.unsplash.com/${ids[(i + 2) % ids.length]}?auto=format&fit=crop&w=1200&q=80`,
  ];
});
